/**
 * How claudep finds and launches `claude`, and the Windows-only shapes it
 * cannot exercise for real on a macOS or Linux host: PATH walking, cmd.exe
 * quoting, signal tables, the Developer Mode hint and alias shim text.
 */
import { describe, expect, test } from "bun:test";
import {
  aliasFiles,
  aliasShim,
  claudeSpawn,
  cmdExeCommand,
  cmdExeQuote,
  credentialsFileHas,
  findClaude,
  symlinkDeniedHint,
  wrapperSignals,
} from "../claudep.ts";

function winDeps(pathVar: string, present: string[]) {
  const set = new Set(present);
  return {
    platform: "win32" as const,
    pathVar,
    exists: (p: string) => set.has(p),
    which: () => null,
  };
}

describe("findClaude", () => {
  test("asks which() off Windows and reports an exe", () => {
    const deps = { platform: "linux" as const, pathVar: "", exists: () => false, which: () => "/usr/bin/claude" };
    expect(findClaude(deps)).toEqual({ bin: "/usr/bin/claude", kind: "exe" });
    expect(findClaude({ ...deps, which: () => null })).toBeUndefined();
  });

  test("walks PATH in order on Windows and prefers claude.exe inside one directory", () => {
    const path = "C:\\a;C:\\b";
    expect(findClaude(winDeps(path, ["C:\\a\\claude.cmd", "C:\\a\\claude.exe"]))).toEqual({
      bin: "C:\\a\\claude.exe",
      kind: "exe",
    });
    expect(findClaude(winDeps(path, ["C:\\a\\claude.cmd", "C:\\b\\claude.exe"]))).toEqual({
      bin: "C:\\a\\claude.cmd",
      kind: "cmd",
    });
    expect(findClaude(winDeps(path, ["C:\\b\\claude.ps1"]))).toEqual({ bin: "C:\\b\\claude.ps1", kind: "ps1" });
    expect(findClaude(winDeps(path, ["C:\\b\\claude"]))).toBeUndefined();
  });
});

describe("cmd.exe quoting", () => {
  // Expected strings are what cross-spawn produces for the same input.
  test.each([
    ["plain", '^"plain^"'],
    ["say hi", '^"say^ hi^"'],
    ['a"b', '^"a\\^"b^"'],
    ["x&y", '^"x^&y^"'],
    ["end\\", '^"end\\\\^"'],
    ["%PATH%", '^"^%PATH^%^"'],
  ])("argument %p, single escape -> %p", (arg, quoted) => {
    expect(cmdExeQuote(arg, false)).toBe(quoted);
  });

  test("double escape for a .cmd target carets the carets again", () => {
    expect(cmdExeQuote("say hi")).toBe('^^^"say^^^ hi^^^"');
    expect(cmdExeQuote("x&y")).toBe('^^^"x^^^&y^^^"');
  });

  test("the command word is caret-escaped and never quoted", () => {
    expect(cmdExeCommand("C:\\npm\\claude.cmd")).toBe("C:\\npm\\claude.cmd");
    expect(cmdExeCommand("C:\\Program Files\\x.cmd")).toBe("C:\\Program^ Files\\x.cmd");
  });
});

describe("claudeSpawn", () => {
  test("runs an exe directly with the arguments untouched", () => {
    expect(claudeSpawn({ bin: "/usr/bin/claude", kind: "exe" }, ["-p", "say hi"])).toEqual({
      cmd: ["/usr/bin/claude", "-p", "say hi"],
      verbatim: false,
    });
  });

  test("runs a .cmd shim through cmd.exe with one quoted command line", () => {
    const r = claudeSpawn({ bin: "C:\\npm\\claude.cmd", kind: "cmd" }, ["-p", "say hi"]);
    expect(r.verbatim).toBe(true);
    expect(r.cmd).toEqual(["cmd.exe", "/d", "/s", "/c", '"C:\\npm\\claude.cmd ^^^"-p^^^" ^^^"say^^^ hi^^^""']);
  });
});

describe("wrapperSignals", () => {
  test("forwards SIGHUP only where it exists", () => {
    expect(wrapperSignals("darwin")).toEqual({ ignore: ["SIGINT"], forward: ["SIGTERM", "SIGHUP"] });
    expect(wrapperSignals("linux")).toEqual({ ignore: ["SIGINT"], forward: ["SIGTERM", "SIGHUP"] });
    expect(wrapperSignals("win32")).toEqual({ ignore: ["SIGINT"], forward: ["SIGTERM"] });
  });
});

describe("symlinkDeniedHint", () => {
  test("names Developer Mode on Windows and the re-run command everywhere", () => {
    const w = symlinkDeniedHint("win32", "work");
    expect(w).toContain("Developer Mode");
    expect(w).toContain("claudep init work");
    const l = symlinkDeniedHint("linux", "work");
    expect(l).not.toContain("Developer Mode");
    expect(l).toContain("claudep init work");
  });
});

describe("credentialsFileHas", () => {
  test("checks for .credentials.json inside the profile and never reads it", () => {
    const seen: string[] = [];
    const exists = (p: string) => {
      seen.push(p);
      return p.endsWith(".credentials.json");
    };
    expect(credentialsFileHas("/p/work", exists)).toBe(true);
    expect(seen).toEqual(["/p/work/.credentials.json"]);
    expect(credentialsFileHas("/p/work", () => false)).toBe(false);
  });
});

describe("alias shims", () => {
  test("sh shim execs bun with the profile and passes arguments through", () => {
    const s = aliasShim("sh", "/repo/claudep.ts", "smoke");
    expect(s.startsWith("#!/bin/sh\n")).toBe(true);
    expect(s).toContain("generated by claudep");
    expect(s).toContain('exec bun "/repo/claudep.ts" run smoke -- "$@"');
  });

  test("cmd shim does the same for cmd.exe and PowerShell, with CRLF endings", () => {
    const s = aliasShim("cmd", "C:\\repo\\claudep.ts", "smoke");
    expect(s.startsWith("@echo off\r\n")).toBe(true);
    expect(s).toContain("REM generated by claudep");
    expect(s).toContain('bun "C:\\repo\\claudep.ts" run smoke -- %*\r\n');
    expect(s).not.toContain("\n\n");
    expect(s.split("\r\n").every((l) => !l.includes("\n"))).toBe(true);
  });

  test("one sh file on POSIX, a .cmd plus the sh file on Windows", () => {
    expect(aliasFiles("/bin", "esmoke", "linux")).toEqual([{ path: "/bin/esmoke", kind: "sh" }]);
    expect(aliasFiles("C:\\bin", "esmoke", "win32")).toEqual([
      { path: "C:\\bin\\esmoke.cmd", kind: "cmd" },
      { path: "C:\\bin\\esmoke", kind: "sh" },
    ]);
  });
});
